lang: ru-RU
encoding: utf-8
url: https://roshchinmu.github.io/
permalink: categories # pretty
highlighter: rouge
markdown: kramdown

# sass:
#   style: :compressed

# https://markshevchenko.pro/articles/github-pages/jekyll/