url: https://roshchinmu.github.io/
permalink: pretty
# kramdown:
#   syntax_highlighter: coderay
#   syntax_highlighter_opts:
#     line_numbers: table
#     bold_every: 5
# markdown: kramdown
# markdown: kramdown
# kramdown: 
#   input: GFM
#   syntax_highlighter: rouge
# theme: minima
# plugins:
#   - jekyll-feed


# theme: minima
# plugins:
#   - jekyll-feed

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "article"

collections:
  sections:
#     permalink: /:collection/:name

# sass:
#   style: :compressed

# https://markshevchenko.pro/articles/github-pages/jekyll/