lang: ru-RU
encoding: utf-8
url: https://roshchinmu.github.io/
permalink: /:title.html #/blog/:title/ #categories # pretty
# highlighter: rouge
# markdown: kramdown
markdown: kramdown
highlighter: rouge
input: GFM

collections:
  staff_members:
    permalink: /:collection/:name

# sass:
#   style: :compressed

# https://markshevchenko.pro/articles/github-pages/jekyll/